CREATE DATABASE QuanLyXetTuyenHocSinh_Database
GO

USE QuanLyXetTuyenHocSinh_Database
GO

-- Thông tin của học sinh 
CREATE TABLE HocSinh
(
MaHocSinh INT IDENTITY PRIMARY KEY,
Cmnd NVARCHAR(15) NOT NULL DEFAULT N'Chưa nhập', -- CMND không thể null
HoTen NVARCHAR(50) NOT NULL, -- Họ và tên không thể null
GioiTinh BIT DEFAULT(1),
NgaySinh DATE NOT NULL DEFAULT 0,
NoiSinh NVARCHAR(100),
DanToc NVARCHAR(25),
TonGiao NVARCHAR(25),
NamTotNghiep NVARCHAR(5),
TenTruongTHPT NVARCHAR(100),
Tinh NVARCHAR(50),
Sdt NVARCHAR(10),
DiaChiLienLac NVARCHAR(150),
HoTenPhuHuynh NVARCHAR(50),
SdtPhuHuynh INT,
GhiChu NVARCHAR(100)

)
GO

-- Một nhân viên có thể có nhiều vị trí khác nhau
CREATE TABLE LoaiNhanVien
(
	MaLoaiNhanVien INT IDENTITY PRIMARY KEY,
	ViTri_CongViec NVARCHAR(100) NOT NULL,
	GhiChu NVARCHAR(100)
)
GO

-- Thông tin nhân viên
CREATE TABLE NhanVien
(
	MaNhanVien INT IDENTITY PRIMARY KEY,
	MaLoaiNhanVien INT NOT NULL, -- Mã loại nhân viên không thể null
	HoTen NVARCHAR(50) NOT NULL, -- Họ tên không thể null
	GioiTinh BIT DEFAULT(1),
	NgaySinh DATE,
	Luong INT,
	AnhNV NVARCHAR(50),
	DiaChi NVARCHAR(150),
	NoiSinh NVARCHAR(100),
	GhiChu NVARCHAR(100),

	FOREIGN KEY(MaLoaiNhanVien) REFERENCES LoaiNhanVien(MaLoaiNhanVien)
	ON UPDATE CASCADE 
)

-- Thông tin điểm học bạ
CREATE TABLE DiemHocBa(
MaDiemHocBa INT PRIMARY KEY NOT NULL,
MaHocSinh INT NOT NULL,
Toan10_HK1 FLOAT NOT NULL DEFAULT 0,Toan10_HK2 FLOAT NOT NULL DEFAULT 0, Toan10_TrungBinhCong FLOAT NOT NULL DEFAULT 0,
Ly10_HK1 FLOAT NOT NULL DEFAULT 0, Ly10_HK2 FLOAT NOT NULL DEFAULT 0, Ly10_TrungBinhCong FLOAT NOT NULL DEFAULT 0,
Hoa10_HK1 FLOAT NOT NULL DEFAULT 0,Hoa10_HK2 FLOAT NOT NULL DEFAULT 0, Hoa10_TrungBinhCong FLOAT NOT NULL DEFAULT 0, 
Sinh10_HK1 FLOAT NOT NULL DEFAULT 0,Sinh10_HK2 FLOAT NOT NULL DEFAULT 0, Sinh10_TrungBinhCong FLOAT NOT NULL DEFAULT 0, 
NguVan10_HK1 FLOAT NOT NULL DEFAULT 0, NguVan10_HK2 FLOAT NOT NULL DEFAULT 0, NguVan10_TrungBinhCong FLOAT NOT NULL DEFAULT 0,
LichSu10_HK1 FLOAT NOT NULL DEFAULT 0, LichSu10_HK2 FLOAT NOT NULL DEFAULT 0,LichSu10_TrungBinhCong FLOAT NOT NULL DEFAULT 0,
DiaLy10_HK1 FLOAT NOT NULL DEFAULT 0, DiaLy10_HK2 FLOAT NOT NULL DEFAULT 0, DiaLy10_TrungBinhCong FLOAT NOT NULL DEFAULT 0,
CongDan10_HK1 FLOAT NOT NULL DEFAULT 0, CongDan10_HK2 FLOAT NOT NULL DEFAULT 0, CongDan10_TrungBinhCong FLOAT NOT NULL DEFAULT 0,
TiengAnh10_HK1 FLOAT NOT NULL DEFAULT 0, TiengAnh10_HK2 FLOAT NOT NULL DEFAULT 0, TiengAnh10_TrungBinhCong FLOAT NOT NULL DEFAULT 0, 
Toan11_HK1 FLOAT NOT NULL DEFAULT 0, Toan11_HK2 FLOAT NOT NULL DEFAULT 0, Toan11_TrungBinhCong FLOAT NOT NULL DEFAULT 0,
Ly11_HK1 FLOAT NOT NULL DEFAULT 0, Ly11_HK2 FLOAT NOT NULL DEFAULT 0, Ly11_TrungBinhCong FLOAT NOT NULL DEFAULT 0,
Hoa11_HK1 FLOAT NOT NULL DEFAULT 0, Hoa11_HK2 FLOAT NOT NULL DEFAULT 0, Hoa11_TrungBinhCong FLOAT NOT NULL DEFAULT 0,
Sinh11_HK1 FLOAT NOT NULL DEFAULT 0, Sinh11_HK2 FLOAT NOT NULL DEFAULT 0, Sinh11_TrungBinhCong FLOAT NOT NULL DEFAULT 0, 
NguVan11_HK1 FLOAT NOT NULL DEFAULT 0, NguVan11_HK2 FLOAT NOT NULL DEFAULT 0, NguVan11_TrungBinhCong FLOAT NOT NULL DEFAULT 0,
LichSu11_HK1 FLOAT NOT NULL DEFAULT 0,LichSu11_HK2 FLOAT NOT NULL DEFAULT 0, LichSu11_TrungBinhCong FLOAT NOT NULL DEFAULT 0,
DiaLy11_HK1 FLOAT NOT NULL DEFAULT 0, DiaLy11_HK2 FLOAT NOT NULL DEFAULT 0, DiaLy11_TrungBinhCong FLOAT NOT NULL DEFAULT 0,
CongDan11_HK1 FLOAT NOT NULL DEFAULT 0, CongDan11_HK2 FLOAT NOT NULL DEFAULT 0, CongDan11_TrungBinhCong FLOAT NOT NULL DEFAULT 0,
TiengAnh11_HK1 FLOAT NOT NULL DEFAULT 0, TiengAnh11_HK2 FLOAT NOT NULL DEFAULT 0, TiengAnh11_TrungBinhCong FLOAT NOT NULL DEFAULT 0,
Toan12_HK1 FLOAT NOT NULL DEFAULT 0, Toan12_HK2 FLOAT NOT NULL DEFAULT 0, Toan12_TrungBinhCong FLOAT NOT NULL DEFAULT 0,
Ly12_HK1 FLOAT NOT NULL DEFAULT 0, Ly12_HK2 FLOAT NOT NULL DEFAULT 0,Ly12_TrungBinhCong FLOAT NOT NULL DEFAULT 0,
Hoa12_HK1 FLOAT NOT NULL DEFAULT 0, Hoa12_HK2 FLOAT NOT NULL DEFAULT 0, Hoa12_TrungBinhCong FLOAT NOT NULL DEFAULT 0,
Sinh12_HK1 FLOAT NOT NULL DEFAULT 0, Sinh12_HK2 FLOAT NOT NULL DEFAULT 0, Sinh12_TrungBinhCong FLOAT NOT NULL DEFAULT 0,
NguVan12_HK1 FLOAT NOT NULL DEFAULT 0, NguVan12_HK2 FLOAT NOT NULL DEFAULT 0, NguVan12_TrungBinhCong FLOAT NOT NULL DEFAULT 0,
LichSu12_HK1 FLOAT NOT NULL DEFAULT 0, LichSu12_HK2 FLOAT NOT NULL DEFAULT 0, LichSu12_TrungBinhCong FLOAT NOT NULL DEFAULT 0,
DiaLy12_HK1 FLOAT NOT NULL DEFAULT 0, DiaLy12_HK2 FLOAT NOT NULL DEFAULT 0, DiaLy12_TrungBinhCong FLOAT NOT NULL DEFAULT 0,
CongDan12_HK1 FLOAT NOT NULL DEFAULT 0, CongDan12_HK2 FLOAT NOT NULL DEFAULT 0, CongDan12_TrungBinhCong FLOAT NOT NULL DEFAULT 0,
TiengAnh12_HK1 FLOAT NOT NULL DEFAULT 0, TiengAnh12_HK2 FLOAT NOT NULL DEFAULT 0, TiengAnh12_TrungBinhCong FLOAT NOT NULL DEFAULT 0,

FOREIGN KEY(MaHocSinh) REFERENCES HocSinh(MaHocSinh)
ON UPDATE CASCADE
)
GO

-- Thông tin ngành học
CREATE TABLE NganhHoc
(
MaNganhHoc NVARCHAR(50) PRIMARY KEY, 
TenNganhHoc NVARCHAR (50) NOT NULL,
ToHopXetTuyen NVARCHAR (50) NOT NULL,
DiemXetTuyen INT NOT NULL,
)
GO

-- Dựa bảo bảng đăng kí xét tuyển, ta có thể biết được
-- học sinh nào có điểm học bạ như thế nào và chọn ngành gì, thuộc tổ hợp xét tuyển gì
CREATE TABLE DangKi_XetTuyen
(
MaXetTuyen INT PRIMARY KEY NOT NULL,
MaDiemHocBa INT NOT NULL,
MaNganhHoc NVARCHAR(50) NOT NULL,
TrangThai NVARCHAR(50),
GhiChu NVARCHAR(100),
FOREIGN KEY(MaDiemHocBa) REFERENCES DiemHocBa(MaDiemHocBa),
FOREIGN KEY(MaNganhHoc) REFERENCES  NganhHoc(MaNganhHoc)

ON UPDATE CASCADE 
)

CREATE TABLE ChiTieuXetTuyen
(
	MaChiTieuXetTuyen INT IDENTITY PRIMARY KEY,
	SoLuongHocSinhXetTuyen INT NOT NULL DEFAULT 0,
	MaNganhHoc NVARCHAR(50) NOT NULL,
	FOREIGN KEY(MaNganhHoc) REFERENCES NganhHoc(MaNganhHoc)

	ON UPDATE CASCADE 
)







