CREATE DATABASE QuanLyXetTuyenHocSinh_Database
GO

USE QuanLyXetTuyenHocSinh_Database
GO

CREATE TABLE HocSinh
(
MaHocSinh INT IDENTITY PRIMARY KEY,
Cmnd NVARCHAR(15)NOT NULL,
HoTen NVARCHAR(50)NOT NULL,
GioiTinh NVARCHAR(20) NOT NULL DEFAULT 'CHUA NHAP',
NgaySinh DATETIME NOT NULL DEFAULT 0,
NoiSinh NVARCHAR(100) DEFAULT 'CHUA NHAP',
DanToc NVARCHAR(25) DEFAULT 'CHUA NHAP',
TonGiao NVARCHAR(25) DEFAULT 'CHUA NHAP',
NamTotNghiep NVARCHAR(5) NOT NULL DEFAULT 'CHUA NHAP',
TenTruongTHPT NVARCHAR(100) DEFAULT 'CHUA NHAP',
TINH NVARCHAR(50)NOT NULL DEFAULT 'CHUA NHAP',
Sdt NVARCHAR(10) NOT NULL DEFAULT 'CHUA NHAP',
DiaChiLienLac NVARCHAR(150) NOT NULL DEFAULT 'CHUA NHAP',
HoTenPhuHuynh NVARCHAR(150) NOT NULL DEFAULT 'CHUA NHAP',
SdtPhuHuynh INT NOT NULL DEFAULT 'CHUA NHAP',
GhiChu NVARCHAR(100)
)
GO

CREATE TABLE LoaiNhanVien
(
	MaLoaiNhanVien INT IDENTITY PRIMARY KEY,
	ViTri_CongViec NVARCHAR(100) NOT NULL,
	GhiChu NVARCHAR(100)
)
GO

CREATE TABLE NhanVien
(
	MaNhanVien INT IDENTITY PRIMARY KEY,
	MaLoaiNhanVien INT NOT NULL,
	FOREIGN KEY(MaLoaiNhanVien) REFERENCES LoaiNhanVien(MaLoaiNhanVien)

	HoTen NVARCHAR(50) NOT NULL,
	GioiTinh NVARCHAR(50) NOT NULL,
	NgaySinh DATETIME NOT NULL,
	NoiSinh NVARCHAR(100) NOT NULL,
	GhiChu NVARCHAR(100)
)


CREATE TABLE DiemHocBa(
MaDiemHocBa INT PRIMARY KEY NOT NULL,
MaHocSinh INT NOT NULL,
FOREIGN KEY(MaHocSinh) REFERENCES HocSinh(MaHocSinh),
Toan10_HK1 FLOAT NOT NULL DEFAULT 0,Toan10_HK2 FLOAT NOT NULL DEFAULT 0, Toan10_TrungBinhCong FLOAT NOT NULL DEFAULT 0,
Ly10_HK1 FLOAT NOT NULL DEFAULT 0, Ly10_HK2 FLOAT NOT NULL DEFAULT 0, Ly10_TrungBinhCong FLOAT NOT NULL DEFAULT 0,
Hoa10_HK1 FLOAT NOT NULL DEFAULT 0,Hoa10_HK2 FLOAT NOT NULL DEFAULT 0, Hoa10_TrungBinhCong FLOAT NOT NULL DEFAULT 0, 
Sinh10_HK1 FLOAT NOT NULL DEFAULT 0,Sinh10_HK2 FLOAT NOT NULL DEFAULT 0, Sinh10_TrungBinhCong FLOAT NOT NULL DEFAULT 0, 
NguVan10_HK1 FLOAT NOT NULL DEFAULT 0, NguVan10_HK2 FLOAT NOT NULL DEFAULT 0, NguVan10_TrungBinhCong FLOAT NOT NULL DEFAULT 0,
LichSu10_HK1 FLOAT NOT NULL DEFAULT 0, LichSu10_HK2 FLOAT NOT NULL DEFAULT 0,LichSu10_TrungBinhCong FLOAT NOT NULL DEFAULT 0,
DiaLy10_HK1 FLOAT NOT NULL DEFAULT 0, DiaLy10_HK2 FLOAT NOT NULL DEFAULT 0, DiaLy10_TrungBinhCong FLOAT NOT NULL DEFAULT 0,
CongDan10_HK1 FLOAT NOT NULL DEFAULT 0, CongDan10_HK2 FLOAT NOT NULL DEFAULT 0, CongDan10_TrungBinhCong FLOAT NOT NULL DEFAULT 0,
TiengAnh10_HK1 FLOAT NOT NULL DEFAULT 0, TiengAnh10_HK2 FLOAT NOT NULL DEFAULT 0, TiengAnh10_TrungBinhCong FLOAT NOT NULL DEFAULT 0, 
Toan11_HK1 FLOAT NOT NULL DEFAULT 0, Toan11_HK2 FLOAT NOT NULL DEFAULT 0, Toan11_TrungBinhCong FLOAT NOT NULL DEFAULT 0,
Ly11_HK1 FLOAT NOT NULL DEFAULT 0, Ly11_HK2 FLOAT NOT NULL DEFAULT 0, Ly11_TrungBinhCong FLOAT NOT NULL DEFAULT 0,
Hoa11_HK1 FLOAT NOT NULL DEFAULT 0, Hoa11_HK2 FLOAT NOT NULL DEFAULT 0, Hoa11_TrungBinhCong FLOAT NOT NULL DEFAULT 0,
Sinh11_HK1 FLOAT NOT NULL DEFAULT 0, Sinh11_HK2 FLOAT NOT NULL DEFAULT 0, Sinh11_TrungBinhCong FLOAT NOT NULL DEFAULT 0, 
NguVan11_HK1 FLOAT NOT NULL DEFAULT 0, NguVan11_HK2 FLOAT NOT NULL DEFAULT 0, NguVan11_TrungBinhCong FLOAT NOT NULL DEFAULT 0,
LichSu11_HK1 FLOAT NOT NULL DEFAULT 0,LichSu11_HK2 FLOAT NOT NULL DEFAULT 0, LichSu11_TrungBinhCong FLOAT NOT NULL DEFAULT 0,
DiaLy11_HK1 FLOAT NOT NULL DEFAULT 0, DiaLy11_HK2 FLOAT NOT NULL DEFAULT 0, DiaLy11_TrungBinhCong FLOAT NOT NULL DEFAULT 0,
CongDan11_HK1 FLOAT NOT NULL DEFAULT 0, CongDan11_HK2 FLOAT NOT NULL DEFAULT 0, CongDan11_TrungBinhCong FLOAT NOT NULL DEFAULT 0,
TiengAnh11_HK1 FLOAT NOT NULL DEFAULT 0, TiengAnh11_HK2 FLOAT NOT NULL DEFAULT 0, TiengAnh11_TrungBinhCong FLOAT NOT NULL DEFAULT 0,
Toan12_HK1 FLOAT NOT NULL DEFAULT 0, Toan12_HK2 FLOAT NOT NULL DEFAULT 0, Toan12_TrungBinhCong FLOAT NOT NULL DEFAULT 0,
Ly12_HK1 FLOAT NOT NULL DEFAULT 0, Ly12_HK2 FLOAT NOT NULL DEFAULT 0,Ly12_TrungBinhCong FLOAT NOT NULL DEFAULT 0,
Hoa12_HK1 FLOAT NOT NULL DEFAULT 0, Hoa12_HK2 FLOAT NOT NULL DEFAULT 0, Hoa12_TrungBinhCong FLOAT NOT NULL DEFAULT 0,
Sinh12_HK1 FLOAT NOT NULL DEFAULT 0, Sinh12_HK2 FLOAT NOT NULL DEFAULT 0, Sinh12_TrungBinhCong FLOAT NOT NULL DEFAULT 0,
NguVan12_HK1 FLOAT NOT NULL DEFAULT 0, NguVan12_HK2 FLOAT NOT NULL DEFAULT 0, NguVan12_TrungBinhCong FLOAT NOT NULL DEFAULT 0,
LichSu12_HK1 FLOAT NOT NULL DEFAULT 0, LichSu12_HK2 FLOAT NOT NULL DEFAULT 0, LichSu12_TrungBinhCong FLOAT NOT NULL DEFAULT 0,
DiaLy12_HK1 FLOAT NOT NULL DEFAULT 0, DiaLy12_HK2 FLOAT NOT NULL DEFAULT 0, DiaLy12_TrungBinhCong FLOAT NOT NULL DEFAULT 0,
CongDan12_HK1 FLOAT NOT NULL DEFAULT 0, CongDan12_HK2 FLOAT NOT NULL DEFAULT 0, CongDan12_TrungBinhCong FLOAT NOT NULL DEFAULT 0,
TiengAnh12_HK1 FLOAT NOT NULL DEFAULT 0, TiengAnh12_HK2 FLOAT NOT NULL DEFAULT 0, TiengAnh12_TrungBinhCong FLOAT NOT NULL DEFAULT 0,
)
GO

CREATE TABLE NganhHoc
(
MaNganhHoc NVARCHAR(50) PRIMARY KEY, 
TenNganhHoc NVARCHAR (50) NOT NULL,
ToHopXetTuyen NVARCHAR (50) NOT NULL,
DiemXetTuyen INT NOT NULL,
)
GO


CREATE TABLE DangKi_XetTuyen
(
MaXetTuyen INT PRIMARY KEY NOT NULL,
MaDiemHocBa INT NOT NULL,
MaNganhHoc NVARCHAR(50) NOT NULL,
TrangThai NVARCHAR(50),
GhiChu NVARCHAR(100),
FOREIGN KEY(MaDiemHocBa) REFERENCES DiemHocBa(MaDiemHocBa),
FOREIGN KEY(MaNganhHoc) REFERENCES  NganhHoc(MaNganhHoc),
)







